/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardRouteRouteImport } from './routes/dashboard/route'
import { Route as OnboardingRouteRouteImport } from './routes/onboarding/route'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as SignUpRouteImport } from './routes/sign-up'
import { Route as ApiCatalogRouteImport } from './routes/api/catalog'
import { Route as AuthCallbackRouteImport } from './routes/auth/callback'
import { Route as AuthConfirmRouteImport } from './routes/auth/confirm'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as DashboardAiStudyRouteImport } from './routes/dashboard/ai-study'
import { Route as DashboardChannelsRouteImport } from './routes/dashboard/channels'
import { Route as DashboardFriendsRouteImport } from './routes/dashboard/friends'
import { Route as DashboardLeaderboardRouteImport } from './routes/dashboard/leaderboard'
import { Route as DashboardLibraryRouteImport } from './routes/dashboard/library'
import { Route as DashboardMyNotesRouteImport } from './routes/dashboard/my-notes'
import { Route as DashboardPricingRouteImport } from './routes/dashboard/pricing'
import { Route as DashboardSettingsRouteImport } from './routes/dashboard/settings'
import { Route as OnboardingAcademicRouteImport } from './routes/onboarding/academic'
import { Route as OnboardingProfileRouteImport } from './routes/onboarding/profile'
import { Route as OnboardingWelcomeRouteImport } from './routes/onboarding/welcome'
import { Route as ApiAiModelsRouteImport } from './routes/api/ai/models'
import { Route as ApiAiStudySourcesRouteImport } from './routes/api/ai/study-sources'
import { Route as ApiAuthRegisterRouteImport } from './routes/api/auth/register'
import { Route as ApiAuthResendRouteImport } from './routes/api/auth/resend'
import { Route as ApiDashboardOverviewRouteImport } from './routes/api/dashboard/overview'
import { Route as ApiLibraryIndexRouteImport } from './routes/api/library/index'
import { Route as ApiLibraryLibraryIdRouteImport } from './routes/api/library/$libraryId'
import { Route as ApiNotesIndexRouteImport } from './routes/api/notes/index'
import { Route as ApiNotesNoteIdRouteImport } from './routes/api/notes/$noteId'
import { Route as ApiPlansIndexRouteImport } from './routes/api/plans/index'
import { Route as ApiPlansPlanIdRouteImport } from './routes/api/plans/$planId'
import { Route as ApiTeachersIndexRouteImport } from './routes/api/teachers/index'
import { Route as ApiUsersMeRouteImport } from './routes/api/users/me'
import { Route as DashboardPlanIndexRouteImport } from './routes/dashboard/plan/index'
import { Route as DashboardPlanPlanIdRouteImport } from './routes/dashboard/plan/$planId'
import { Route as DashboardPlanCreateRouteImport } from './routes/dashboard/plan/create'
import { Route as DashboardTeachersIndexRouteImport } from './routes/dashboard/teachers/index'
import { Route as ApiAiSessionsIndexRouteImport } from './routes/api/ai/sessions/index'
import { Route as ApiAiSessionsSessionIdRouteImport } from './routes/api/ai/sessions/$sessionId'
import { Route as DashboardPlanPlanIdIndexRouteImport } from './routes/dashboard/plan/$planId.index'
import { Route as DashboardPlanEditPlanIdRouteImport } from './routes/dashboard/plan/edit.$planId'
import { Route as ApiAiAssessmentPlanIdDayNumberRouteImport } from './routes/api/ai/assessment.$planId.$dayNumber'
import { Route as ApiAiAssessmentAnswerAttemptIdRouteImport } from './routes/api/ai/assessment.answer.$attemptId'
import { Route as ApiAiAssessmentCompleteAttemptIdRouteImport } from './routes/api/ai/assessment.complete.$attemptId'
import { Route as ApiAiChatPlanIdDayNumberRouteImport } from './routes/api/ai/chat.$planId.$dayNumber'
import { Route as ApiAiContentPlanIdDayNumberRouteImport } from './routes/api/ai/content.$planId.$dayNumber'
import { Route as ApiAiContextPlanIdDayNumberRouteImport } from './routes/api/ai/context.$planId.$dayNumber'
import { Route as ApiAiLearningPlanIdDayNumberRouteImport } from './routes/api/ai/learning.$planId.$dayNumber'
import { Route as ApiAiRespondPlanIdDayNumberRouteImport } from './routes/api/ai/respond.$planId.$dayNumber'
import { Route as ApiAiSessionsSessionIdAssessmentRouteImport } from './routes/api/ai/sessions/$sessionId.assessment'
import { Route as ApiAiSessionsSessionIdRespondRouteImport } from './routes/api/ai/sessions/$sessionId.respond'
import { Route as DashboardPlanPlanIdDayDayNumberRouteImport } from './routes/dashboard/plan/$planId.day.$dayNumber'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRouteRoute = DashboardRouteRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRouteRoute = OnboardingRouteRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const SignUpRoute = SignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCatalogRoute = ApiCatalogRouteImport.update({
  id: '/api/catalog',
  path: '/api/catalog',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthConfirmRoute = AuthConfirmRouteImport.update({
  id: '/auth/confirm',
  path: '/auth/confirm',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardAiStudyRoute = DashboardAiStudyRouteImport.update({
  id: '/ai-study',
  path: '/ai-study',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardChannelsRoute = DashboardChannelsRouteImport.update({
  id: '/channels',
  path: '/channels',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardFriendsRoute = DashboardFriendsRouteImport.update({
  id: '/friends',
  path: '/friends',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardLeaderboardRoute = DashboardLeaderboardRouteImport.update({
  id: '/leaderboard',
  path: '/leaderboard',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardLibraryRoute = DashboardLibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardMyNotesRoute = DashboardMyNotesRouteImport.update({
  id: '/my-notes',
  path: '/my-notes',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardPricingRoute = DashboardPricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardSettingsRoute = DashboardSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const OnboardingAcademicRoute = OnboardingAcademicRouteImport.update({
  id: '/academic',
  path: '/academic',
  getParentRoute: () => OnboardingRouteRoute,
} as any)
const OnboardingProfileRoute = OnboardingProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => OnboardingRouteRoute,
} as any)
const OnboardingWelcomeRoute = OnboardingWelcomeRouteImport.update({
  id: '/welcome',
  path: '/welcome',
  getParentRoute: () => OnboardingRouteRoute,
} as any)
const ApiAiModelsRoute = ApiAiModelsRouteImport.update({
  id: '/api/ai/models',
  path: '/api/ai/models',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAiStudySourcesRoute = ApiAiStudySourcesRouteImport.update({
  id: '/api/ai/study-sources',
  path: '/api/ai/study-sources',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthRegisterRoute = ApiAuthRegisterRouteImport.update({
  id: '/api/auth/register',
  path: '/api/auth/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthResendRoute = ApiAuthResendRouteImport.update({
  id: '/api/auth/resend',
  path: '/api/auth/resend',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDashboardOverviewRoute = ApiDashboardOverviewRouteImport.update({
  id: '/api/dashboard/overview',
  path: '/api/dashboard/overview',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLibraryIndexRoute = ApiLibraryIndexRouteImport.update({
  id: '/api/library/',
  path: '/api/library/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLibraryLibraryIdRoute = ApiLibraryLibraryIdRouteImport.update({
  id: '/api/library/$libraryId',
  path: '/api/library/$libraryId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiNotesIndexRoute = ApiNotesIndexRouteImport.update({
  id: '/api/notes/',
  path: '/api/notes/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiNotesNoteIdRoute = ApiNotesNoteIdRouteImport.update({
  id: '/api/notes/$noteId',
  path: '/api/notes/$noteId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPlansIndexRoute = ApiPlansIndexRouteImport.update({
  id: '/api/plans/',
  path: '/api/plans/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPlansPlanIdRoute = ApiPlansPlanIdRouteImport.update({
  id: '/api/plans/$planId',
  path: '/api/plans/$planId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTeachersIndexRoute = ApiTeachersIndexRouteImport.update({
  id: '/api/teachers/',
  path: '/api/teachers/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUsersMeRoute = ApiUsersMeRouteImport.update({
  id: '/api/users/me',
  path: '/api/users/me',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardPlanIndexRoute = DashboardPlanIndexRouteImport.update({
  id: '/plan/',
  path: '/plan/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardPlanPlanIdRoute = DashboardPlanPlanIdRouteImport.update({
  id: '/plan/$planId',
  path: '/plan/$planId',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardPlanCreateRoute = DashboardPlanCreateRouteImport.update({
  id: '/plan/create',
  path: '/plan/create',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardTeachersIndexRoute = DashboardTeachersIndexRouteImport.update({
  id: '/teachers/',
  path: '/teachers/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const ApiAiSessionsIndexRoute = ApiAiSessionsIndexRouteImport.update({
  id: '/api/ai/sessions/',
  path: '/api/ai/sessions/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAiSessionsSessionIdRoute = ApiAiSessionsSessionIdRouteImport.update({
  id: '/api/ai/sessions/$sessionId',
  path: '/api/ai/sessions/$sessionId',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardPlanPlanIdIndexRoute =
  DashboardPlanPlanIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => DashboardPlanPlanIdRoute,
  } as any)
const DashboardPlanEditPlanIdRoute = DashboardPlanEditPlanIdRouteImport.update({
  id: '/plan/edit/$planId',
  path: '/plan/edit/$planId',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const ApiAiAssessmentPlanIdDayNumberRoute =
  ApiAiAssessmentPlanIdDayNumberRouteImport.update({
    id: '/api/ai/assessment/$planId/$dayNumber',
    path: '/api/ai/assessment/$planId/$dayNumber',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiAiAssessmentAnswerAttemptIdRoute =
  ApiAiAssessmentAnswerAttemptIdRouteImport.update({
    id: '/api/ai/assessment/answer/$attemptId',
    path: '/api/ai/assessment/answer/$attemptId',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiAiAssessmentCompleteAttemptIdRoute =
  ApiAiAssessmentCompleteAttemptIdRouteImport.update({
    id: '/api/ai/assessment/complete/$attemptId',
    path: '/api/ai/assessment/complete/$attemptId',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiAiChatPlanIdDayNumberRoute =
  ApiAiChatPlanIdDayNumberRouteImport.update({
    id: '/api/ai/chat/$planId/$dayNumber',
    path: '/api/ai/chat/$planId/$dayNumber',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiAiContentPlanIdDayNumberRoute =
  ApiAiContentPlanIdDayNumberRouteImport.update({
    id: '/api/ai/content/$planId/$dayNumber',
    path: '/api/ai/content/$planId/$dayNumber',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiAiContextPlanIdDayNumberRoute =
  ApiAiContextPlanIdDayNumberRouteImport.update({
    id: '/api/ai/context/$planId/$dayNumber',
    path: '/api/ai/context/$planId/$dayNumber',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiAiLearningPlanIdDayNumberRoute =
  ApiAiLearningPlanIdDayNumberRouteImport.update({
    id: '/api/ai/learning/$planId/$dayNumber',
    path: '/api/ai/learning/$planId/$dayNumber',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiAiRespondPlanIdDayNumberRoute =
  ApiAiRespondPlanIdDayNumberRouteImport.update({
    id: '/api/ai/respond/$planId/$dayNumber',
    path: '/api/ai/respond/$planId/$dayNumber',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiAiSessionsSessionIdAssessmentRoute =
  ApiAiSessionsSessionIdAssessmentRouteImport.update({
    id: '/assessment',
    path: '/assessment',
    getParentRoute: () => ApiAiSessionsSessionIdRoute,
  } as any)
const ApiAiSessionsSessionIdRespondRoute =
  ApiAiSessionsSessionIdRespondRouteImport.update({
    id: '/respond',
    path: '/respond',
    getParentRoute: () => ApiAiSessionsSessionIdRoute,
  } as any)
const DashboardPlanPlanIdDayDayNumberRoute =
  DashboardPlanPlanIdDayDayNumberRouteImport.update({
    id: '/day/$dayNumber',
    path: '/day/$dayNumber',
    getParentRoute: () => DashboardPlanPlanIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/onboarding': typeof OnboardingRouteRouteWithChildren
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/api/catalog': typeof ApiCatalogRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/confirm': typeof AuthConfirmRoute
  '/dashboard/ai-study': typeof DashboardAiStudyRoute
  '/dashboard/channels': typeof DashboardChannelsRoute
  '/dashboard/friends': typeof DashboardFriendsRoute
  '/dashboard/leaderboard': typeof DashboardLeaderboardRoute
  '/dashboard/library': typeof DashboardLibraryRoute
  '/dashboard/my-notes': typeof DashboardMyNotesRoute
  '/dashboard/pricing': typeof DashboardPricingRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/onboarding/academic': typeof OnboardingAcademicRoute
  '/onboarding/profile': typeof OnboardingProfileRoute
  '/onboarding/welcome': typeof OnboardingWelcomeRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/api/ai/models': typeof ApiAiModelsRoute
  '/api/ai/study-sources': typeof ApiAiStudySourcesRoute
  '/api/auth/register': typeof ApiAuthRegisterRoute
  '/api/auth/resend': typeof ApiAuthResendRoute
  '/api/dashboard/overview': typeof ApiDashboardOverviewRoute
  '/api/library/$libraryId': typeof ApiLibraryLibraryIdRoute
  '/api/notes/$noteId': typeof ApiNotesNoteIdRoute
  '/api/plans/$planId': typeof ApiPlansPlanIdRoute
  '/api/users/me': typeof ApiUsersMeRoute
  '/dashboard/plan/$planId': typeof DashboardPlanPlanIdRouteWithChildren
  '/dashboard/plan/create': typeof DashboardPlanCreateRoute
  '/api/library/': typeof ApiLibraryIndexRoute
  '/api/notes/': typeof ApiNotesIndexRoute
  '/api/plans/': typeof ApiPlansIndexRoute
  '/api/teachers/': typeof ApiTeachersIndexRoute
  '/dashboard/plan/': typeof DashboardPlanIndexRoute
  '/dashboard/teachers/': typeof DashboardTeachersIndexRoute
  '/api/ai/sessions/$sessionId': typeof ApiAiSessionsSessionIdRouteWithChildren
  '/dashboard/plan/edit/$planId': typeof DashboardPlanEditPlanIdRoute
  '/api/ai/sessions/': typeof ApiAiSessionsIndexRoute
  '/dashboard/plan/$planId/': typeof DashboardPlanPlanIdIndexRoute
  '/api/ai/assessment/$planId/$dayNumber': typeof ApiAiAssessmentPlanIdDayNumberRoute
  '/api/ai/assessment/answer/$attemptId': typeof ApiAiAssessmentAnswerAttemptIdRoute
  '/api/ai/assessment/complete/$attemptId': typeof ApiAiAssessmentCompleteAttemptIdRoute
  '/api/ai/chat/$planId/$dayNumber': typeof ApiAiChatPlanIdDayNumberRoute
  '/api/ai/content/$planId/$dayNumber': typeof ApiAiContentPlanIdDayNumberRoute
  '/api/ai/context/$planId/$dayNumber': typeof ApiAiContextPlanIdDayNumberRoute
  '/api/ai/learning/$planId/$dayNumber': typeof ApiAiLearningPlanIdDayNumberRoute
  '/api/ai/respond/$planId/$dayNumber': typeof ApiAiRespondPlanIdDayNumberRoute
  '/api/ai/sessions/$sessionId/assessment': typeof ApiAiSessionsSessionIdAssessmentRoute
  '/api/ai/sessions/$sessionId/respond': typeof ApiAiSessionsSessionIdRespondRoute
  '/dashboard/plan/$planId/day/$dayNumber': typeof DashboardPlanPlanIdDayDayNumberRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/onboarding': typeof OnboardingRouteRouteWithChildren
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/api/catalog': typeof ApiCatalogRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/confirm': typeof AuthConfirmRoute
  '/dashboard/ai-study': typeof DashboardAiStudyRoute
  '/dashboard/channels': typeof DashboardChannelsRoute
  '/dashboard/friends': typeof DashboardFriendsRoute
  '/dashboard/leaderboard': typeof DashboardLeaderboardRoute
  '/dashboard/library': typeof DashboardLibraryRoute
  '/dashboard/my-notes': typeof DashboardMyNotesRoute
  '/dashboard/pricing': typeof DashboardPricingRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/onboarding/academic': typeof OnboardingAcademicRoute
  '/onboarding/profile': typeof OnboardingProfileRoute
  '/onboarding/welcome': typeof OnboardingWelcomeRoute
  '/dashboard': typeof DashboardIndexRoute
  '/api/ai/models': typeof ApiAiModelsRoute
  '/api/ai/study-sources': typeof ApiAiStudySourcesRoute
  '/api/auth/register': typeof ApiAuthRegisterRoute
  '/api/auth/resend': typeof ApiAuthResendRoute
  '/api/dashboard/overview': typeof ApiDashboardOverviewRoute
  '/api/library/$libraryId': typeof ApiLibraryLibraryIdRoute
  '/api/notes/$noteId': typeof ApiNotesNoteIdRoute
  '/api/plans/$planId': typeof ApiPlansPlanIdRoute
  '/api/users/me': typeof ApiUsersMeRoute
  '/dashboard/plan/create': typeof DashboardPlanCreateRoute
  '/api/library': typeof ApiLibraryIndexRoute
  '/api/notes': typeof ApiNotesIndexRoute
  '/api/plans': typeof ApiPlansIndexRoute
  '/api/teachers': typeof ApiTeachersIndexRoute
  '/dashboard/plan': typeof DashboardPlanIndexRoute
  '/dashboard/teachers': typeof DashboardTeachersIndexRoute
  '/api/ai/sessions/$sessionId': typeof ApiAiSessionsSessionIdRouteWithChildren
  '/dashboard/plan/edit/$planId': typeof DashboardPlanEditPlanIdRoute
  '/api/ai/sessions': typeof ApiAiSessionsIndexRoute
  '/dashboard/plan/$planId': typeof DashboardPlanPlanIdIndexRoute
  '/api/ai/assessment/$planId/$dayNumber': typeof ApiAiAssessmentPlanIdDayNumberRoute
  '/api/ai/assessment/answer/$attemptId': typeof ApiAiAssessmentAnswerAttemptIdRoute
  '/api/ai/assessment/complete/$attemptId': typeof ApiAiAssessmentCompleteAttemptIdRoute
  '/api/ai/chat/$planId/$dayNumber': typeof ApiAiChatPlanIdDayNumberRoute
  '/api/ai/content/$planId/$dayNumber': typeof ApiAiContentPlanIdDayNumberRoute
  '/api/ai/context/$planId/$dayNumber': typeof ApiAiContextPlanIdDayNumberRoute
  '/api/ai/learning/$planId/$dayNumber': typeof ApiAiLearningPlanIdDayNumberRoute
  '/api/ai/respond/$planId/$dayNumber': typeof ApiAiRespondPlanIdDayNumberRoute
  '/api/ai/sessions/$sessionId/assessment': typeof ApiAiSessionsSessionIdAssessmentRoute
  '/api/ai/sessions/$sessionId/respond': typeof ApiAiSessionsSessionIdRespondRoute
  '/dashboard/plan/$planId/day/$dayNumber': typeof DashboardPlanPlanIdDayDayNumberRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/onboarding': typeof OnboardingRouteRouteWithChildren
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/api/catalog': typeof ApiCatalogRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/confirm': typeof AuthConfirmRoute
  '/dashboard/ai-study': typeof DashboardAiStudyRoute
  '/dashboard/channels': typeof DashboardChannelsRoute
  '/dashboard/friends': typeof DashboardFriendsRoute
  '/dashboard/leaderboard': typeof DashboardLeaderboardRoute
  '/dashboard/library': typeof DashboardLibraryRoute
  '/dashboard/my-notes': typeof DashboardMyNotesRoute
  '/dashboard/pricing': typeof DashboardPricingRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/onboarding/academic': typeof OnboardingAcademicRoute
  '/onboarding/profile': typeof OnboardingProfileRoute
  '/onboarding/welcome': typeof OnboardingWelcomeRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/api/ai/models': typeof ApiAiModelsRoute
  '/api/ai/study-sources': typeof ApiAiStudySourcesRoute
  '/api/auth/register': typeof ApiAuthRegisterRoute
  '/api/auth/resend': typeof ApiAuthResendRoute
  '/api/dashboard/overview': typeof ApiDashboardOverviewRoute
  '/api/library/$libraryId': typeof ApiLibraryLibraryIdRoute
  '/api/notes/$noteId': typeof ApiNotesNoteIdRoute
  '/api/plans/$planId': typeof ApiPlansPlanIdRoute
  '/api/users/me': typeof ApiUsersMeRoute
  '/dashboard/plan/$planId': typeof DashboardPlanPlanIdRouteWithChildren
  '/dashboard/plan/create': typeof DashboardPlanCreateRoute
  '/api/library/': typeof ApiLibraryIndexRoute
  '/api/notes/': typeof ApiNotesIndexRoute
  '/api/plans/': typeof ApiPlansIndexRoute
  '/api/teachers/': typeof ApiTeachersIndexRoute
  '/dashboard/plan/': typeof DashboardPlanIndexRoute
  '/dashboard/teachers/': typeof DashboardTeachersIndexRoute
  '/api/ai/sessions/$sessionId': typeof ApiAiSessionsSessionIdRouteWithChildren
  '/dashboard/plan/edit/$planId': typeof DashboardPlanEditPlanIdRoute
  '/api/ai/sessions/': typeof ApiAiSessionsIndexRoute
  '/dashboard/plan/$planId/': typeof DashboardPlanPlanIdIndexRoute
  '/api/ai/assessment/$planId/$dayNumber': typeof ApiAiAssessmentPlanIdDayNumberRoute
  '/api/ai/assessment/answer/$attemptId': typeof ApiAiAssessmentAnswerAttemptIdRoute
  '/api/ai/assessment/complete/$attemptId': typeof ApiAiAssessmentCompleteAttemptIdRoute
  '/api/ai/chat/$planId/$dayNumber': typeof ApiAiChatPlanIdDayNumberRoute
  '/api/ai/content/$planId/$dayNumber': typeof ApiAiContentPlanIdDayNumberRoute
  '/api/ai/context/$planId/$dayNumber': typeof ApiAiContextPlanIdDayNumberRoute
  '/api/ai/learning/$planId/$dayNumber': typeof ApiAiLearningPlanIdDayNumberRoute
  '/api/ai/respond/$planId/$dayNumber': typeof ApiAiRespondPlanIdDayNumberRoute
  '/api/ai/sessions/$sessionId/assessment': typeof ApiAiSessionsSessionIdAssessmentRoute
  '/api/ai/sessions/$sessionId/respond': typeof ApiAiSessionsSessionIdRespondRoute
  '/dashboard/plan/$planId/day/$dayNumber': typeof DashboardPlanPlanIdDayDayNumberRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/onboarding'
    | '/sign-in'
    | '/sign-up'
    | '/api/catalog'
    | '/auth/callback'
    | '/auth/confirm'
    | '/dashboard/ai-study'
    | '/dashboard/channels'
    | '/dashboard/friends'
    | '/dashboard/leaderboard'
    | '/dashboard/library'
    | '/dashboard/my-notes'
    | '/dashboard/pricing'
    | '/dashboard/settings'
    | '/onboarding/academic'
    | '/onboarding/profile'
    | '/onboarding/welcome'
    | '/dashboard/'
    | '/api/ai/models'
    | '/api/ai/study-sources'
    | '/api/auth/register'
    | '/api/auth/resend'
    | '/api/dashboard/overview'
    | '/api/library/$libraryId'
    | '/api/notes/$noteId'
    | '/api/plans/$planId'
    | '/api/users/me'
    | '/dashboard/plan/$planId'
    | '/dashboard/plan/create'
    | '/api/library/'
    | '/api/notes/'
    | '/api/plans/'
    | '/api/teachers/'
    | '/dashboard/plan/'
    | '/dashboard/teachers/'
    | '/api/ai/sessions/$sessionId'
    | '/dashboard/plan/edit/$planId'
    | '/api/ai/sessions/'
    | '/dashboard/plan/$planId/'
    | '/api/ai/assessment/$planId/$dayNumber'
    | '/api/ai/assessment/answer/$attemptId'
    | '/api/ai/assessment/complete/$attemptId'
    | '/api/ai/chat/$planId/$dayNumber'
    | '/api/ai/content/$planId/$dayNumber'
    | '/api/ai/context/$planId/$dayNumber'
    | '/api/ai/learning/$planId/$dayNumber'
    | '/api/ai/respond/$planId/$dayNumber'
    | '/api/ai/sessions/$sessionId/assessment'
    | '/api/ai/sessions/$sessionId/respond'
    | '/dashboard/plan/$planId/day/$dayNumber'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/onboarding'
    | '/sign-in'
    | '/sign-up'
    | '/api/catalog'
    | '/auth/callback'
    | '/auth/confirm'
    | '/dashboard/ai-study'
    | '/dashboard/channels'
    | '/dashboard/friends'
    | '/dashboard/leaderboard'
    | '/dashboard/library'
    | '/dashboard/my-notes'
    | '/dashboard/pricing'
    | '/dashboard/settings'
    | '/onboarding/academic'
    | '/onboarding/profile'
    | '/onboarding/welcome'
    | '/dashboard'
    | '/api/ai/models'
    | '/api/ai/study-sources'
    | '/api/auth/register'
    | '/api/auth/resend'
    | '/api/dashboard/overview'
    | '/api/library/$libraryId'
    | '/api/notes/$noteId'
    | '/api/plans/$planId'
    | '/api/users/me'
    | '/dashboard/plan/create'
    | '/api/library'
    | '/api/notes'
    | '/api/plans'
    | '/api/teachers'
    | '/dashboard/plan'
    | '/dashboard/teachers'
    | '/api/ai/sessions/$sessionId'
    | '/dashboard/plan/edit/$planId'
    | '/api/ai/sessions'
    | '/dashboard/plan/$planId'
    | '/api/ai/assessment/$planId/$dayNumber'
    | '/api/ai/assessment/answer/$attemptId'
    | '/api/ai/assessment/complete/$attemptId'
    | '/api/ai/chat/$planId/$dayNumber'
    | '/api/ai/content/$planId/$dayNumber'
    | '/api/ai/context/$planId/$dayNumber'
    | '/api/ai/learning/$planId/$dayNumber'
    | '/api/ai/respond/$planId/$dayNumber'
    | '/api/ai/sessions/$sessionId/assessment'
    | '/api/ai/sessions/$sessionId/respond'
    | '/dashboard/plan/$planId/day/$dayNumber'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/onboarding'
    | '/sign-in'
    | '/sign-up'
    | '/api/catalog'
    | '/auth/callback'
    | '/auth/confirm'
    | '/dashboard/ai-study'
    | '/dashboard/channels'
    | '/dashboard/friends'
    | '/dashboard/leaderboard'
    | '/dashboard/library'
    | '/dashboard/my-notes'
    | '/dashboard/pricing'
    | '/dashboard/settings'
    | '/onboarding/academic'
    | '/onboarding/profile'
    | '/onboarding/welcome'
    | '/dashboard/'
    | '/api/ai/models'
    | '/api/ai/study-sources'
    | '/api/auth/register'
    | '/api/auth/resend'
    | '/api/dashboard/overview'
    | '/api/library/$libraryId'
    | '/api/notes/$noteId'
    | '/api/plans/$planId'
    | '/api/users/me'
    | '/dashboard/plan/$planId'
    | '/dashboard/plan/create'
    | '/api/library/'
    | '/api/notes/'
    | '/api/plans/'
    | '/api/teachers/'
    | '/dashboard/plan/'
    | '/dashboard/teachers/'
    | '/api/ai/sessions/$sessionId'
    | '/dashboard/plan/edit/$planId'
    | '/api/ai/sessions/'
    | '/dashboard/plan/$planId/'
    | '/api/ai/assessment/$planId/$dayNumber'
    | '/api/ai/assessment/answer/$attemptId'
    | '/api/ai/assessment/complete/$attemptId'
    | '/api/ai/chat/$planId/$dayNumber'
    | '/api/ai/content/$planId/$dayNumber'
    | '/api/ai/context/$planId/$dayNumber'
    | '/api/ai/learning/$planId/$dayNumber'
    | '/api/ai/respond/$planId/$dayNumber'
    | '/api/ai/sessions/$sessionId/assessment'
    | '/api/ai/sessions/$sessionId/respond'
    | '/dashboard/plan/$planId/day/$dayNumber'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRouteRoute: typeof DashboardRouteRouteWithChildren
  OnboardingRouteRoute: typeof OnboardingRouteRouteWithChildren
  SignInRoute: typeof SignInRoute
  SignUpRoute: typeof SignUpRoute
  ApiCatalogRoute: typeof ApiCatalogRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  AuthConfirmRoute: typeof AuthConfirmRoute
  ApiAiModelsRoute: typeof ApiAiModelsRoute
  ApiAiStudySourcesRoute: typeof ApiAiStudySourcesRoute
  ApiAuthRegisterRoute: typeof ApiAuthRegisterRoute
  ApiAuthResendRoute: typeof ApiAuthResendRoute
  ApiDashboardOverviewRoute: typeof ApiDashboardOverviewRoute
  ApiLibraryLibraryIdRoute: typeof ApiLibraryLibraryIdRoute
  ApiNotesNoteIdRoute: typeof ApiNotesNoteIdRoute
  ApiPlansPlanIdRoute: typeof ApiPlansPlanIdRoute
  ApiUsersMeRoute: typeof ApiUsersMeRoute
  ApiLibraryIndexRoute: typeof ApiLibraryIndexRoute
  ApiNotesIndexRoute: typeof ApiNotesIndexRoute
  ApiPlansIndexRoute: typeof ApiPlansIndexRoute
  ApiTeachersIndexRoute: typeof ApiTeachersIndexRoute
  ApiAiSessionsSessionIdRoute: typeof ApiAiSessionsSessionIdRouteWithChildren
  ApiAiSessionsIndexRoute: typeof ApiAiSessionsIndexRoute
  ApiAiAssessmentPlanIdDayNumberRoute: typeof ApiAiAssessmentPlanIdDayNumberRoute
  ApiAiAssessmentAnswerAttemptIdRoute: typeof ApiAiAssessmentAnswerAttemptIdRoute
  ApiAiAssessmentCompleteAttemptIdRoute: typeof ApiAiAssessmentCompleteAttemptIdRoute
  ApiAiChatPlanIdDayNumberRoute: typeof ApiAiChatPlanIdDayNumberRoute
  ApiAiContentPlanIdDayNumberRoute: typeof ApiAiContentPlanIdDayNumberRoute
  ApiAiContextPlanIdDayNumberRoute: typeof ApiAiContextPlanIdDayNumberRoute
  ApiAiLearningPlanIdDayNumberRoute: typeof ApiAiLearningPlanIdDayNumberRoute
  ApiAiRespondPlanIdDayNumberRoute: typeof ApiAiRespondPlanIdDayNumberRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-up': {
      id: '/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof SignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/catalog': {
      id: '/api/catalog'
      path: '/api/catalog'
      fullPath: '/api/catalog'
      preLoaderRoute: typeof ApiCatalogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/confirm': {
      id: '/auth/confirm'
      path: '/auth/confirm'
      fullPath: '/auth/confirm'
      preLoaderRoute: typeof AuthConfirmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/ai-study': {
      id: '/dashboard/ai-study'
      path: '/ai-study'
      fullPath: '/dashboard/ai-study'
      preLoaderRoute: typeof DashboardAiStudyRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/channels': {
      id: '/dashboard/channels'
      path: '/channels'
      fullPath: '/dashboard/channels'
      preLoaderRoute: typeof DashboardChannelsRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/friends': {
      id: '/dashboard/friends'
      path: '/friends'
      fullPath: '/dashboard/friends'
      preLoaderRoute: typeof DashboardFriendsRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/leaderboard': {
      id: '/dashboard/leaderboard'
      path: '/leaderboard'
      fullPath: '/dashboard/leaderboard'
      preLoaderRoute: typeof DashboardLeaderboardRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/library': {
      id: '/dashboard/library'
      path: '/library'
      fullPath: '/dashboard/library'
      preLoaderRoute: typeof DashboardLibraryRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/my-notes': {
      id: '/dashboard/my-notes'
      path: '/my-notes'
      fullPath: '/dashboard/my-notes'
      preLoaderRoute: typeof DashboardMyNotesRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/pricing': {
      id: '/dashboard/pricing'
      path: '/pricing'
      fullPath: '/dashboard/pricing'
      preLoaderRoute: typeof DashboardPricingRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/settings': {
      id: '/dashboard/settings'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof DashboardSettingsRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/onboarding/academic': {
      id: '/onboarding/academic'
      path: '/academic'
      fullPath: '/onboarding/academic'
      preLoaderRoute: typeof OnboardingAcademicRouteImport
      parentRoute: typeof OnboardingRouteRoute
    }
    '/onboarding/profile': {
      id: '/onboarding/profile'
      path: '/profile'
      fullPath: '/onboarding/profile'
      preLoaderRoute: typeof OnboardingProfileRouteImport
      parentRoute: typeof OnboardingRouteRoute
    }
    '/onboarding/welcome': {
      id: '/onboarding/welcome'
      path: '/welcome'
      fullPath: '/onboarding/welcome'
      preLoaderRoute: typeof OnboardingWelcomeRouteImport
      parentRoute: typeof OnboardingRouteRoute
    }
    '/api/ai/models': {
      id: '/api/ai/models'
      path: '/api/ai/models'
      fullPath: '/api/ai/models'
      preLoaderRoute: typeof ApiAiModelsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ai/study-sources': {
      id: '/api/ai/study-sources'
      path: '/api/ai/study-sources'
      fullPath: '/api/ai/study-sources'
      preLoaderRoute: typeof ApiAiStudySourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/register': {
      id: '/api/auth/register'
      path: '/api/auth/register'
      fullPath: '/api/auth/register'
      preLoaderRoute: typeof ApiAuthRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/resend': {
      id: '/api/auth/resend'
      path: '/api/auth/resend'
      fullPath: '/api/auth/resend'
      preLoaderRoute: typeof ApiAuthResendRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/dashboard/overview': {
      id: '/api/dashboard/overview'
      path: '/api/dashboard/overview'
      fullPath: '/api/dashboard/overview'
      preLoaderRoute: typeof ApiDashboardOverviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/library/': {
      id: '/api/library/'
      path: '/api/library'
      fullPath: '/api/library/'
      preLoaderRoute: typeof ApiLibraryIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/library/$libraryId': {
      id: '/api/library/$libraryId'
      path: '/api/library/$libraryId'
      fullPath: '/api/library/$libraryId'
      preLoaderRoute: typeof ApiLibraryLibraryIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/notes/': {
      id: '/api/notes/'
      path: '/api/notes'
      fullPath: '/api/notes/'
      preLoaderRoute: typeof ApiNotesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/notes/$noteId': {
      id: '/api/notes/$noteId'
      path: '/api/notes/$noteId'
      fullPath: '/api/notes/$noteId'
      preLoaderRoute: typeof ApiNotesNoteIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/plans/': {
      id: '/api/plans/'
      path: '/api/plans'
      fullPath: '/api/plans/'
      preLoaderRoute: typeof ApiPlansIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/plans/$planId': {
      id: '/api/plans/$planId'
      path: '/api/plans/$planId'
      fullPath: '/api/plans/$planId'
      preLoaderRoute: typeof ApiPlansPlanIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/teachers/': {
      id: '/api/teachers/'
      path: '/api/teachers'
      fullPath: '/api/teachers/'
      preLoaderRoute: typeof ApiTeachersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/users/me': {
      id: '/api/users/me'
      path: '/api/users/me'
      fullPath: '/api/users/me'
      preLoaderRoute: typeof ApiUsersMeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/plan/': {
      id: '/dashboard/plan/'
      path: '/plan'
      fullPath: '/dashboard/plan/'
      preLoaderRoute: typeof DashboardPlanIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/plan/$planId': {
      id: '/dashboard/plan/$planId'
      path: '/plan/$planId'
      fullPath: '/dashboard/plan/$planId'
      preLoaderRoute: typeof DashboardPlanPlanIdRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/plan/create': {
      id: '/dashboard/plan/create'
      path: '/plan/create'
      fullPath: '/dashboard/plan/create'
      preLoaderRoute: typeof DashboardPlanCreateRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/teachers/': {
      id: '/dashboard/teachers/'
      path: '/teachers'
      fullPath: '/dashboard/teachers/'
      preLoaderRoute: typeof DashboardTeachersIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/api/ai/sessions/': {
      id: '/api/ai/sessions/'
      path: '/api/ai/sessions'
      fullPath: '/api/ai/sessions/'
      preLoaderRoute: typeof ApiAiSessionsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ai/sessions/$sessionId': {
      id: '/api/ai/sessions/$sessionId'
      path: '/api/ai/sessions/$sessionId'
      fullPath: '/api/ai/sessions/$sessionId'
      preLoaderRoute: typeof ApiAiSessionsSessionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/plan/$planId/': {
      id: '/dashboard/plan/$planId/'
      path: '/'
      fullPath: '/dashboard/plan/$planId/'
      preLoaderRoute: typeof DashboardPlanPlanIdIndexRouteImport
      parentRoute: typeof DashboardPlanPlanIdRoute
    }
    '/dashboard/plan/edit/$planId': {
      id: '/dashboard/plan/edit/$planId'
      path: '/plan/edit/$planId'
      fullPath: '/dashboard/plan/edit/$planId'
      preLoaderRoute: typeof DashboardPlanEditPlanIdRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/api/ai/assessment/$planId/$dayNumber': {
      id: '/api/ai/assessment/$planId/$dayNumber'
      path: '/api/ai/assessment/$planId/$dayNumber'
      fullPath: '/api/ai/assessment/$planId/$dayNumber'
      preLoaderRoute: typeof ApiAiAssessmentPlanIdDayNumberRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ai/assessment/answer/$attemptId': {
      id: '/api/ai/assessment/answer/$attemptId'
      path: '/api/ai/assessment/answer/$attemptId'
      fullPath: '/api/ai/assessment/answer/$attemptId'
      preLoaderRoute: typeof ApiAiAssessmentAnswerAttemptIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ai/assessment/complete/$attemptId': {
      id: '/api/ai/assessment/complete/$attemptId'
      path: '/api/ai/assessment/complete/$attemptId'
      fullPath: '/api/ai/assessment/complete/$attemptId'
      preLoaderRoute: typeof ApiAiAssessmentCompleteAttemptIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ai/chat/$planId/$dayNumber': {
      id: '/api/ai/chat/$planId/$dayNumber'
      path: '/api/ai/chat/$planId/$dayNumber'
      fullPath: '/api/ai/chat/$planId/$dayNumber'
      preLoaderRoute: typeof ApiAiChatPlanIdDayNumberRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ai/content/$planId/$dayNumber': {
      id: '/api/ai/content/$planId/$dayNumber'
      path: '/api/ai/content/$planId/$dayNumber'
      fullPath: '/api/ai/content/$planId/$dayNumber'
      preLoaderRoute: typeof ApiAiContentPlanIdDayNumberRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ai/context/$planId/$dayNumber': {
      id: '/api/ai/context/$planId/$dayNumber'
      path: '/api/ai/context/$planId/$dayNumber'
      fullPath: '/api/ai/context/$planId/$dayNumber'
      preLoaderRoute: typeof ApiAiContextPlanIdDayNumberRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ai/learning/$planId/$dayNumber': {
      id: '/api/ai/learning/$planId/$dayNumber'
      path: '/api/ai/learning/$planId/$dayNumber'
      fullPath: '/api/ai/learning/$planId/$dayNumber'
      preLoaderRoute: typeof ApiAiLearningPlanIdDayNumberRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ai/respond/$planId/$dayNumber': {
      id: '/api/ai/respond/$planId/$dayNumber'
      path: '/api/ai/respond/$planId/$dayNumber'
      fullPath: '/api/ai/respond/$planId/$dayNumber'
      preLoaderRoute: typeof ApiAiRespondPlanIdDayNumberRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ai/sessions/$sessionId/assessment': {
      id: '/api/ai/sessions/$sessionId/assessment'
      path: '/assessment'
      fullPath: '/api/ai/sessions/$sessionId/assessment'
      preLoaderRoute: typeof ApiAiSessionsSessionIdAssessmentRouteImport
      parentRoute: typeof ApiAiSessionsSessionIdRoute
    }
    '/api/ai/sessions/$sessionId/respond': {
      id: '/api/ai/sessions/$sessionId/respond'
      path: '/respond'
      fullPath: '/api/ai/sessions/$sessionId/respond'
      preLoaderRoute: typeof ApiAiSessionsSessionIdRespondRouteImport
      parentRoute: typeof ApiAiSessionsSessionIdRoute
    }
    '/dashboard/plan/$planId/day/$dayNumber': {
      id: '/dashboard/plan/$planId/day/$dayNumber'
      path: '/day/$dayNumber'
      fullPath: '/dashboard/plan/$planId/day/$dayNumber'
      preLoaderRoute: typeof DashboardPlanPlanIdDayDayNumberRouteImport
      parentRoute: typeof DashboardPlanPlanIdRoute
    }
  }
}

interface DashboardPlanPlanIdRouteChildren {
  DashboardPlanPlanIdIndexRoute: typeof DashboardPlanPlanIdIndexRoute
  DashboardPlanPlanIdDayDayNumberRoute: typeof DashboardPlanPlanIdDayDayNumberRoute
}

const DashboardPlanPlanIdRouteChildren: DashboardPlanPlanIdRouteChildren = {
  DashboardPlanPlanIdIndexRoute: DashboardPlanPlanIdIndexRoute,
  DashboardPlanPlanIdDayDayNumberRoute: DashboardPlanPlanIdDayDayNumberRoute,
}

const DashboardPlanPlanIdRouteWithChildren =
  DashboardPlanPlanIdRoute._addFileChildren(DashboardPlanPlanIdRouteChildren)

interface DashboardRouteRouteChildren {
  DashboardAiStudyRoute: typeof DashboardAiStudyRoute
  DashboardChannelsRoute: typeof DashboardChannelsRoute
  DashboardFriendsRoute: typeof DashboardFriendsRoute
  DashboardLeaderboardRoute: typeof DashboardLeaderboardRoute
  DashboardLibraryRoute: typeof DashboardLibraryRoute
  DashboardMyNotesRoute: typeof DashboardMyNotesRoute
  DashboardPricingRoute: typeof DashboardPricingRoute
  DashboardSettingsRoute: typeof DashboardSettingsRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardPlanPlanIdRoute: typeof DashboardPlanPlanIdRouteWithChildren
  DashboardPlanCreateRoute: typeof DashboardPlanCreateRoute
  DashboardPlanIndexRoute: typeof DashboardPlanIndexRoute
  DashboardTeachersIndexRoute: typeof DashboardTeachersIndexRoute
  DashboardPlanEditPlanIdRoute: typeof DashboardPlanEditPlanIdRoute
}

const DashboardRouteRouteChildren: DashboardRouteRouteChildren = {
  DashboardAiStudyRoute: DashboardAiStudyRoute,
  DashboardChannelsRoute: DashboardChannelsRoute,
  DashboardFriendsRoute: DashboardFriendsRoute,
  DashboardLeaderboardRoute: DashboardLeaderboardRoute,
  DashboardLibraryRoute: DashboardLibraryRoute,
  DashboardMyNotesRoute: DashboardMyNotesRoute,
  DashboardPricingRoute: DashboardPricingRoute,
  DashboardSettingsRoute: DashboardSettingsRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardPlanPlanIdRoute: DashboardPlanPlanIdRouteWithChildren,
  DashboardPlanCreateRoute: DashboardPlanCreateRoute,
  DashboardPlanIndexRoute: DashboardPlanIndexRoute,
  DashboardTeachersIndexRoute: DashboardTeachersIndexRoute,
  DashboardPlanEditPlanIdRoute: DashboardPlanEditPlanIdRoute,
}

const DashboardRouteRouteWithChildren = DashboardRouteRoute._addFileChildren(
  DashboardRouteRouteChildren,
)

interface OnboardingRouteRouteChildren {
  OnboardingAcademicRoute: typeof OnboardingAcademicRoute
  OnboardingProfileRoute: typeof OnboardingProfileRoute
  OnboardingWelcomeRoute: typeof OnboardingWelcomeRoute
}

const OnboardingRouteRouteChildren: OnboardingRouteRouteChildren = {
  OnboardingAcademicRoute: OnboardingAcademicRoute,
  OnboardingProfileRoute: OnboardingProfileRoute,
  OnboardingWelcomeRoute: OnboardingWelcomeRoute,
}

const OnboardingRouteRouteWithChildren = OnboardingRouteRoute._addFileChildren(
  OnboardingRouteRouteChildren,
)

interface ApiAiSessionsSessionIdRouteChildren {
  ApiAiSessionsSessionIdAssessmentRoute: typeof ApiAiSessionsSessionIdAssessmentRoute
  ApiAiSessionsSessionIdRespondRoute: typeof ApiAiSessionsSessionIdRespondRoute
}

const ApiAiSessionsSessionIdRouteChildren: ApiAiSessionsSessionIdRouteChildren =
  {
    ApiAiSessionsSessionIdAssessmentRoute:
      ApiAiSessionsSessionIdAssessmentRoute,
    ApiAiSessionsSessionIdRespondRoute: ApiAiSessionsSessionIdRespondRoute,
  }

const ApiAiSessionsSessionIdRouteWithChildren =
  ApiAiSessionsSessionIdRoute._addFileChildren(
    ApiAiSessionsSessionIdRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRouteRoute: DashboardRouteRouteWithChildren,
  OnboardingRouteRoute: OnboardingRouteRouteWithChildren,
  SignInRoute: SignInRoute,
  SignUpRoute: SignUpRoute,
  ApiCatalogRoute: ApiCatalogRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  AuthConfirmRoute: AuthConfirmRoute,
  ApiAiModelsRoute: ApiAiModelsRoute,
  ApiAiStudySourcesRoute: ApiAiStudySourcesRoute,
  ApiAuthRegisterRoute: ApiAuthRegisterRoute,
  ApiAuthResendRoute: ApiAuthResendRoute,
  ApiDashboardOverviewRoute: ApiDashboardOverviewRoute,
  ApiLibraryLibraryIdRoute: ApiLibraryLibraryIdRoute,
  ApiNotesNoteIdRoute: ApiNotesNoteIdRoute,
  ApiPlansPlanIdRoute: ApiPlansPlanIdRoute,
  ApiUsersMeRoute: ApiUsersMeRoute,
  ApiLibraryIndexRoute: ApiLibraryIndexRoute,
  ApiNotesIndexRoute: ApiNotesIndexRoute,
  ApiPlansIndexRoute: ApiPlansIndexRoute,
  ApiTeachersIndexRoute: ApiTeachersIndexRoute,
  ApiAiSessionsSessionIdRoute: ApiAiSessionsSessionIdRouteWithChildren,
  ApiAiSessionsIndexRoute: ApiAiSessionsIndexRoute,
  ApiAiAssessmentPlanIdDayNumberRoute: ApiAiAssessmentPlanIdDayNumberRoute,
  ApiAiAssessmentAnswerAttemptIdRoute: ApiAiAssessmentAnswerAttemptIdRoute,
  ApiAiAssessmentCompleteAttemptIdRoute: ApiAiAssessmentCompleteAttemptIdRoute,
  ApiAiChatPlanIdDayNumberRoute: ApiAiChatPlanIdDayNumberRoute,
  ApiAiContentPlanIdDayNumberRoute: ApiAiContentPlanIdDayNumberRoute,
  ApiAiContextPlanIdDayNumberRoute: ApiAiContextPlanIdDayNumberRoute,
  ApiAiLearningPlanIdDayNumberRoute: ApiAiLearningPlanIdDayNumberRoute,
  ApiAiRespondPlanIdDayNumberRoute: ApiAiRespondPlanIdDayNumberRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
