/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SkillsSkillIdRouteImport } from './routes/skills/$skillId'
import { Route as ApiModelHandshakeRouteImport } from './routes/api/model/handshake'
import { Route as SkillsAssessmentsSkillIdRouteImport } from './routes/skills/assessments.$skillId'
import { Route as SkillsChatSkillIdRouteImport } from './routes/skills/chat.$skillId'
import { Route as SkillsPlanSkillIdRouteImport } from './routes/skills/plan.$skillId'
import { Route as ApiModelSkillsIndexRouteImport } from './routes/api/model/skills/index'
import { Route as ApiModelSkillsSkillIdRouteImport } from './routes/api/model/skills/$skillId'
import { Route as ApiModelSkillsSkillIdAssessmentsRouteImport } from './routes/api/model/skills/$skillId/assessments'
import { Route as ApiModelSkillsSkillIdPlanRouteImport } from './routes/api/model/skills/$skillId/plan'
import { Route as ApiModelSkillsSkillIdQueryRouteImport } from './routes/api/model/skills/$skillId/query'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SkillsSkillIdRoute = SkillsSkillIdRouteImport.update({
  id: '/skills/$skillId',
  path: '/skills/$skillId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiModelHandshakeRoute = ApiModelHandshakeRouteImport.update({
  id: '/api/model/handshake',
  path: '/api/model/handshake',
  getParentRoute: () => rootRouteImport,
} as any)
const SkillsAssessmentsSkillIdRoute =
  SkillsAssessmentsSkillIdRouteImport.update({
    id: '/skills/assessments/$skillId',
    path: '/skills/assessments/$skillId',
    getParentRoute: () => rootRouteImport,
  } as any)
const SkillsChatSkillIdRoute = SkillsChatSkillIdRouteImport.update({
  id: '/skills/chat/$skillId',
  path: '/skills/chat/$skillId',
  getParentRoute: () => rootRouteImport,
} as any)
const SkillsPlanSkillIdRoute = SkillsPlanSkillIdRouteImport.update({
  id: '/skills/plan/$skillId',
  path: '/skills/plan/$skillId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiModelSkillsIndexRoute = ApiModelSkillsIndexRouteImport.update({
  id: '/api/model/skills/',
  path: '/api/model/skills/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiModelSkillsSkillIdRoute = ApiModelSkillsSkillIdRouteImport.update({
  id: '/api/model/skills/$skillId',
  path: '/api/model/skills/$skillId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiModelSkillsSkillIdAssessmentsRoute =
  ApiModelSkillsSkillIdAssessmentsRouteImport.update({
    id: '/assessments',
    path: '/assessments',
    getParentRoute: () => ApiModelSkillsSkillIdRoute,
  } as any)
const ApiModelSkillsSkillIdPlanRoute =
  ApiModelSkillsSkillIdPlanRouteImport.update({
    id: '/plan',
    path: '/plan',
    getParentRoute: () => ApiModelSkillsSkillIdRoute,
  } as any)
const ApiModelSkillsSkillIdQueryRoute =
  ApiModelSkillsSkillIdQueryRouteImport.update({
    id: '/query',
    path: '/query',
    getParentRoute: () => ApiModelSkillsSkillIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/skills/$skillId': typeof SkillsSkillIdRoute
  '/api/model/handshake': typeof ApiModelHandshakeRoute
  '/skills/assessments/$skillId': typeof SkillsAssessmentsSkillIdRoute
  '/skills/chat/$skillId': typeof SkillsChatSkillIdRoute
  '/skills/plan/$skillId': typeof SkillsPlanSkillIdRoute
  '/api/model/skills/$skillId': typeof ApiModelSkillsSkillIdRouteWithChildren
  '/api/model/skills/': typeof ApiModelSkillsIndexRoute
  '/api/model/skills/$skillId/assessments': typeof ApiModelSkillsSkillIdAssessmentsRoute
  '/api/model/skills/$skillId/plan': typeof ApiModelSkillsSkillIdPlanRoute
  '/api/model/skills/$skillId/query': typeof ApiModelSkillsSkillIdQueryRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/skills/$skillId': typeof SkillsSkillIdRoute
  '/api/model/handshake': typeof ApiModelHandshakeRoute
  '/skills/assessments/$skillId': typeof SkillsAssessmentsSkillIdRoute
  '/skills/chat/$skillId': typeof SkillsChatSkillIdRoute
  '/skills/plan/$skillId': typeof SkillsPlanSkillIdRoute
  '/api/model/skills/$skillId': typeof ApiModelSkillsSkillIdRouteWithChildren
  '/api/model/skills': typeof ApiModelSkillsIndexRoute
  '/api/model/skills/$skillId/assessments': typeof ApiModelSkillsSkillIdAssessmentsRoute
  '/api/model/skills/$skillId/plan': typeof ApiModelSkillsSkillIdPlanRoute
  '/api/model/skills/$skillId/query': typeof ApiModelSkillsSkillIdQueryRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/skills/$skillId': typeof SkillsSkillIdRoute
  '/api/model/handshake': typeof ApiModelHandshakeRoute
  '/skills/assessments/$skillId': typeof SkillsAssessmentsSkillIdRoute
  '/skills/chat/$skillId': typeof SkillsChatSkillIdRoute
  '/skills/plan/$skillId': typeof SkillsPlanSkillIdRoute
  '/api/model/skills/$skillId': typeof ApiModelSkillsSkillIdRouteWithChildren
  '/api/model/skills/': typeof ApiModelSkillsIndexRoute
  '/api/model/skills/$skillId/assessments': typeof ApiModelSkillsSkillIdAssessmentsRoute
  '/api/model/skills/$skillId/plan': typeof ApiModelSkillsSkillIdPlanRoute
  '/api/model/skills/$skillId/query': typeof ApiModelSkillsSkillIdQueryRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/skills/$skillId'
    | '/api/model/handshake'
    | '/skills/assessments/$skillId'
    | '/skills/chat/$skillId'
    | '/skills/plan/$skillId'
    | '/api/model/skills/$skillId'
    | '/api/model/skills/'
    | '/api/model/skills/$skillId/assessments'
    | '/api/model/skills/$skillId/plan'
    | '/api/model/skills/$skillId/query'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/skills/$skillId'
    | '/api/model/handshake'
    | '/skills/assessments/$skillId'
    | '/skills/chat/$skillId'
    | '/skills/plan/$skillId'
    | '/api/model/skills/$skillId'
    | '/api/model/skills'
    | '/api/model/skills/$skillId/assessments'
    | '/api/model/skills/$skillId/plan'
    | '/api/model/skills/$skillId/query'
  id:
    | '__root__'
    | '/'
    | '/skills/$skillId'
    | '/api/model/handshake'
    | '/skills/assessments/$skillId'
    | '/skills/chat/$skillId'
    | '/skills/plan/$skillId'
    | '/api/model/skills/$skillId'
    | '/api/model/skills/'
    | '/api/model/skills/$skillId/assessments'
    | '/api/model/skills/$skillId/plan'
    | '/api/model/skills/$skillId/query'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SkillsSkillIdRoute: typeof SkillsSkillIdRoute
  ApiModelHandshakeRoute: typeof ApiModelHandshakeRoute
  SkillsAssessmentsSkillIdRoute: typeof SkillsAssessmentsSkillIdRoute
  SkillsChatSkillIdRoute: typeof SkillsChatSkillIdRoute
  SkillsPlanSkillIdRoute: typeof SkillsPlanSkillIdRoute
  ApiModelSkillsSkillIdRoute: typeof ApiModelSkillsSkillIdRouteWithChildren
  ApiModelSkillsIndexRoute: typeof ApiModelSkillsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/skills/$skillId': {
      id: '/skills/$skillId'
      path: '/skills/$skillId'
      fullPath: '/skills/$skillId'
      preLoaderRoute: typeof SkillsSkillIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/model/handshake': {
      id: '/api/model/handshake'
      path: '/api/model/handshake'
      fullPath: '/api/model/handshake'
      preLoaderRoute: typeof ApiModelHandshakeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/skills/assessments/$skillId': {
      id: '/skills/assessments/$skillId'
      path: '/skills/assessments/$skillId'
      fullPath: '/skills/assessments/$skillId'
      preLoaderRoute: typeof SkillsAssessmentsSkillIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/skills/chat/$skillId': {
      id: '/skills/chat/$skillId'
      path: '/skills/chat/$skillId'
      fullPath: '/skills/chat/$skillId'
      preLoaderRoute: typeof SkillsChatSkillIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/skills/plan/$skillId': {
      id: '/skills/plan/$skillId'
      path: '/skills/plan/$skillId'
      fullPath: '/skills/plan/$skillId'
      preLoaderRoute: typeof SkillsPlanSkillIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/model/skills/': {
      id: '/api/model/skills/'
      path: '/api/model/skills'
      fullPath: '/api/model/skills/'
      preLoaderRoute: typeof ApiModelSkillsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/model/skills/$skillId': {
      id: '/api/model/skills/$skillId'
      path: '/api/model/skills/$skillId'
      fullPath: '/api/model/skills/$skillId'
      preLoaderRoute: typeof ApiModelSkillsSkillIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/model/skills/$skillId/assessments': {
      id: '/api/model/skills/$skillId/assessments'
      path: '/assessments'
      fullPath: '/api/model/skills/$skillId/assessments'
      preLoaderRoute: typeof ApiModelSkillsSkillIdAssessmentsRouteImport
      parentRoute: typeof ApiModelSkillsSkillIdRoute
    }
    '/api/model/skills/$skillId/plan': {
      id: '/api/model/skills/$skillId/plan'
      path: '/plan'
      fullPath: '/api/model/skills/$skillId/plan'
      preLoaderRoute: typeof ApiModelSkillsSkillIdPlanRouteImport
      parentRoute: typeof ApiModelSkillsSkillIdRoute
    }
    '/api/model/skills/$skillId/query': {
      id: '/api/model/skills/$skillId/query'
      path: '/query'
      fullPath: '/api/model/skills/$skillId/query'
      preLoaderRoute: typeof ApiModelSkillsSkillIdQueryRouteImport
      parentRoute: typeof ApiModelSkillsSkillIdRoute
    }
  }
}

interface ApiModelSkillsSkillIdRouteChildren {
  ApiModelSkillsSkillIdAssessmentsRoute: typeof ApiModelSkillsSkillIdAssessmentsRoute
  ApiModelSkillsSkillIdPlanRoute: typeof ApiModelSkillsSkillIdPlanRoute
  ApiModelSkillsSkillIdQueryRoute: typeof ApiModelSkillsSkillIdQueryRoute
}

const ApiModelSkillsSkillIdRouteChildren: ApiModelSkillsSkillIdRouteChildren = {
  ApiModelSkillsSkillIdAssessmentsRoute: ApiModelSkillsSkillIdAssessmentsRoute,
  ApiModelSkillsSkillIdPlanRoute: ApiModelSkillsSkillIdPlanRoute,
  ApiModelSkillsSkillIdQueryRoute: ApiModelSkillsSkillIdQueryRoute,
}

const ApiModelSkillsSkillIdRouteWithChildren =
  ApiModelSkillsSkillIdRoute._addFileChildren(
    ApiModelSkillsSkillIdRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SkillsSkillIdRoute: SkillsSkillIdRoute,
  ApiModelHandshakeRoute: ApiModelHandshakeRoute,
  SkillsAssessmentsSkillIdRoute: SkillsAssessmentsSkillIdRoute,
  SkillsChatSkillIdRoute: SkillsChatSkillIdRoute,
  SkillsPlanSkillIdRoute: SkillsPlanSkillIdRoute,
  ApiModelSkillsSkillIdRoute: ApiModelSkillsSkillIdRouteWithChildren,
  ApiModelSkillsIndexRoute: ApiModelSkillsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
