import {
  Accessibility,
  Activity,
  ArrowLeft,
  ArrowRight,
  BadgeCheck,
  BarChart3,
  Bookmark,
  BookOpen,
  Briefcase,
  Building2,
  CalendarCheck,
  CalendarCheck2,
  Camera,
  Check,
  CheckCheck,
  ChevronDown,
  Circle,
  CircleCheck,
  ClipboardCheck,
  ClipboardList,
  Compass,
  CreditCard,
  Feather,
  FileText,
  Flag,
  FlaskConical,
  FolderOpen,
  Globe,
  GraduationCap,
  Heart,
  Layers,
  LayoutDashboard,
  LayoutTemplate,
  Library,
  Link as LinkIcon,
  Lock,
  LogOut,
  Mail,
  Menu,
  MessageCircle,
  Minus,
  Monitor,
  Moon,
  NotebookPen,
  PanelLeftClose,
  PanelLeftOpen,
  Play,
  Plus,
  Presentation,
  Radio,
  Route,
  Ruler,
  ScanText,
  School,
  Settings,
  ShieldCheck,
  Sparkles,
  Smartphone,
  Target,
  TrendingUp,
  Trophy,
  Upload,
  User,
  UserCheck,
  Users,
  UsersRound,
  Wallet,
  X,
} from "lucide-react";
import type { LucideIcon, LucideProps } from "lucide-react";

const iconsByName = {
  accessibility: Accessibility,
  activity: Activity,
  "arrow-left": ArrowLeft,
  "arrow-right": ArrowRight,
  "badge-check": BadgeCheck,
  "bar-chart-3": BarChart3,
  bookmark: Bookmark,
  "book-open": BookOpen,
  briefcase: Briefcase,
  "building-2": Building2,
  "calendar-check": CalendarCheck,
  "calendar-check-2": CalendarCheck2,
  camera: Camera,
  check: Check,
  "check-check": CheckCheck,
  "chevron-down": ChevronDown,
  circle: Circle,
  "circle-check": CircleCheck,
  "clipboard-check": ClipboardCheck,
  "clipboard-list": ClipboardList,
  compass: Compass,
  "credit-card": CreditCard,
  feather: Feather,
  "file-text": FileText,
  flag: Flag,
  "flask-conical": FlaskConical,
  "folder-open": FolderOpen,
  globe: Globe,
  "graduation-cap": GraduationCap,
  heart: Heart,
  layers: Layers,
  "layout-dashboard": LayoutDashboard,
  "layout-template": LayoutTemplate,
  library: Library,
  link: LinkIcon,
  lock: Lock,
  "log-out": LogOut,
  mail: Mail,
  menu: Menu,
  "message-circle": MessageCircle,
  minus: Minus,
  monitor: Monitor,
  moon: Moon,
  "notebook-pen": NotebookPen,
  "panel-left-close": PanelLeftClose,
  "panel-left-open": PanelLeftOpen,
  play: Play,
  plus: Plus,
  presentation: Presentation,
  radio: Radio,
  route: Route,
  ruler: Ruler,
  "scan-text": ScanText,
  school: School,
  settings: Settings,
  "shield-check": ShieldCheck,
  sparkles: Sparkles,
  smartphone: Smartphone,
  target: Target,
  "trending-up": TrendingUp,
  trophy: Trophy,
  upload: Upload,
  user: User,
  "user-check": UserCheck,
  users: Users,
  "users-round": UsersRound,
  wallet: Wallet,
  x: X,
} satisfies Record<string, LucideIcon>;

export type IconName = keyof typeof iconsByName;

export interface IconProps extends Omit<LucideProps, "ref"> {
  name: IconName;
}

export function Icon({ name, size = 20, ...props }: IconProps) {
  const LucideIconComponent = iconsByName[name];
  return <LucideIconComponent size={size} {...props} />;
}
